// Generated by IcedCoffeeScript 1.3.3d
(function() {

  exports.make = function(req, res) {
    var arr, breadcrumb, cp, fs, i, link, path, root, _i, _ref;
    fs = require('fs');
    path = require('path');
    cp = require('child_process');
    root = path.dirname(path.dirname(path.dirname(__dirname))) + '/';
    path = root + req.params[0];
    arr = req.params[0].split('/');
    link = '';
    breadcrumb = [
      {
        text: 'Browse',
        link: '/'
      }
    ];
    for (i = _i = 0, _ref = arr.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (arr[i] !== '') {
        link += '/' + arr[i];
        breadcrumb[breadcrumb.length] = {
          text: arr[i],
          link: link
        };
      }
    }
    return res.render('make', {
      title: 'MakeStatus - ' + req.params[0],
      dir: req.params[0],
      breadcrumb: breadcrumb,
      target: req.params[1],
      nav: {
        make: 'active'
      }
    });
  };

}).call(this);
