// Generated by IcedCoffeeScript 1.3.3f
(function() {
  var iced, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  exports.upload = function(req, res) {
    var addr, cp, err, fields, files, form, formidable, fs, nurl, p, path, root, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    fs = require('fs');
    path = require('path');
    nurl = require('url');
    formidable = require('formidable');
    cp = require('child_process');
    root = path.dirname(path.dirname(path.dirname(__dirname))) + '/';
    p = root + req.params[0];
    p = path.dirname(p);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    addr = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
    form = new formidable.IncomingForm();
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "routes/upload.iced",
        funcname: "upload"
      });
      form.parse(req, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            fields = arguments[1];
            return files = arguments[2];
          };
        })(),
        lineno: 36
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (err) {
        console.error(err.message);
        res.end();
        return;
      }
      console.log(fields);
      console.log(files);
      return res.end();
    });
  };

}).call(this);
