// Generated by IcedCoffeeScript 1.3.3f
(function() {

  exports.view = function(req, res, next) {
    var arr, cp, fs, link, path, root;
    fs = require('fs');
    path = require('path');
    cp = require('child_process');
    root = path.dirname(path.dirname(path.dirname(__dirname))) + '/';
    path = root + req.params[0];
    if (!fs.existsSync(path) || !fs.statSync(path).isFile()) return next();
    arr = req.params[0].split('/');
    link = '';
    return res.render('view', {
      title: 'View - ' + req.params[0],
      dir: req.params[0]
    });
  };

}).call(this);
