// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var assert, fs, mangledyaml, yaml;

  assert = require('assert');

  yaml = require('js-yaml');

  fs = require('fs');

  mangledyaml = require('../unmangle');

  describe('a.yaml', function() {
    return it('should pass', function() {
      var result;
      result = mangledyaml.unmangle(fs.readFileSync('test/files/a.mangled.yaml', 'utf8'), 'result=mail');
      return assert.equal(result.trim(), fs.readFileSync('test/files/a.unmangled.yaml', 'utf8').trim());
    });
  });

  describe('b.yaml', function() {
    return it('should pass', function() {
      var result;
      result = mangledyaml.unmangle(fs.readFileSync('test/files/b.mangled.yaml', 'utf8'), 'result=browser');
      return assert.equal(result.trim(), fs.readFileSync('test/files/b.unmangled.yaml', 'utf8').trim());
    });
  });

}).call(this);
